[workspace]
resolver = "3"
members = ["a01-hello", "a02-client-messages", "a03-io", "a04-network-io", "a05-server-client", "a06-in-depth", "a07-select", "a08-streams", "mini-redis-server"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
bytes = "1"
